projects/scottiess/config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from
    end
  end

  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'

   match '/course',  :to=> 'static_pages#courses'
    match '/bugs',  :to=> 'static_pages#bug'
    match '/teach',  :to=> 'static_pages#teach'
    match '/html5',  :to=> 'static_pages#les1'
     match '/android',  :to=> 'static_pages#les2'
 match '/home',  :to=> 'static_pages#home'
  root      :to=> 'users#index'

end

projects/scottiess/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

projects/scottiess/app/views/shared/_feed.html.erb
<script type="text/JavaScript">
  <!--
  function timedRefresh(timeoutPeriod) {
  setTimeout("location.reload(true);",timeoutPeriod);
  }
  //   -->
 </script>
<body onload="JavaScript:timedRefresh(60000);">
<% if @feed_items.any? %>
  <ol class="microposts span6">
    <%= render :partial=> 'shared/feed_item', :collection=> @feed_items %>
  </ol></br>
<% end %>

projects/scottiess/app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
    <span class="content">
        <%= link_to (image_tag feed_item.user.image_url, :size => "50x50", :id=>"feedpicture"), feed_item.user, :title=> feed_item.user.username %>
    <% if feed_item.is_reply_to? %>
      <a href="users/<%=feed_item.in_reply_to.username%>"><%="@#{feed_item.in_reply_to.username}"%></a>
      <%= wrap(feed_item.content.gsub(/\A^@\w+/, "")) %>
    <% else %>
      <%= wrap(feed_item.content.gsub(/\A^@\w+/, ""))%>
    <% end %>
  </span>
  <span class="timestamp">
    <%= link_to feed_item.user.username, feed_item.user, :title=> "View Profile"%> posted
    <%= time_ago_in_words(feed_item.created_at) %> ago
    <% if feed_item.is_reply_to? %>
       to <%= feed_item.in_reply_to.username %>.
    <% end %>
  </span>
  <% if !current_user?(feed_item.user)%>
    <%= link_to image_tag("like.png", :size => "20x20", :id=>"usernavb" ), vote_micropost_path(feed_item), :method=> "post", :title=> "Vote me please! Thanks :)" %>
  <% end %>
  <% if current_user?(feed_item.user) %>
    <%= link_to image_tag("delete.png", :size => "20x20", :id=>"usernavb" ), feed_item, :method=> :delete,
      :data=> { :confirm=> "You sure?" },
      :title=> "Aww. Don't delete me :(" %>
  <% end %>
  <span class="timestamp">
    </br>
      Popularity: <%= feed_item.reputation_for(:votes).to_i %>
    </span>
  </br>
</li>

projects/scottiess/app/views/shared/_feed_mobile.html.erb
<% if @feed_items.any? %>
  <ol class="microposts span6">
    <%= render :partial=> 'shared/feed_item', :collection=> @feed_items %>
  </ol></br>
</br>
<div id="page">
</div>
<% end %>

projects/scottiess/app/views/shared/_home.html.erb
<% provide(:title, 'Home') %>
</div>
</div>
</div>
<div id="clouds">

	<div class="cloud x1"></div>
		
	<!-- Time for multiple clouds to dance around -->
	<div class="cloud x2"></div>
<center><%=image_tag("http://i43.tinypic.com/2zp4aaf.png")%>

	<div class="cloud x3"></div>

	<div class="cloud x4"></div>
	<a href="http://orangeapps.weebly.com/news.html" class="btn btn-large btn-info ">Latest Updates </a><br>
 </br>Copyright 2013 OrangeApps © All Rights Reserved. </center> 

      
 




</body>

projects/scottiess/app/views/shared/_home_mobile.html.erb
<body id="max">
<div class="rows mgin">
<div class="span4 offset3">
    <em><b>Sign in</b></em>
  </br>
</br>
</br>
</br>
    <%= form_for(:sessions, :url=> '/enter') do |f| %>

      <%= f.label :username%>
      <%= f.text_field :username %>

      <%= f.label :password %>
      <%= f.password_field :password %>

     <alignleft> <%= f.submit "Sign in", :class=> "btn btn-large btn-primary" %>
    <% end %>
      </br>
    </br>
  </br>
 </div>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br></div>
</body>

projects/scottiess/app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', :object=> f.object %>
    <div class="field">
        <%= f.text_area :content, :placeholder=> "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", :class=> "btn btn-large btn-primary" %>
    

<% end %>

projects/scottiess/app/views/shared/_parser_form.html.erb
<%= form_tag '/parser' do %>
  <!--%= render 'shared/error_messages', :object => f.object %-->
  <div class="field">
    <%= text_area_tag 'command', params[:command],:maxlength=> 140, :placeholder=> "Holla, holla, playa! Wazzup?" %>
  </div>
  <%= submit_tag "Post", :class=> "btn btn-large btn-primary", :name=> nil %>
<% end %>

projects/scottiess/app/views/shared/_post_form.html.erb
<%= form_tag '/parser' do %>
  <!--%= render 'shared/error_messages', :object => f.object %-->
  <div class="field">
    <%= text_area_tag 'command', params[:command],:maxlength=> 140, :placeholder=> "Holla, holla, playa! Wazzup?" %>
  </div>
  <%= submit_tag "Post", :class=> "btn btn-large btn-primary", :name=> nil %>
<% end %>

projects/scottiess/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<center>
<div class="stats">
  <div class="stats">
  <a href="<%=user_path(@user)%>">
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
    </strong>
    Posts
  </a>
  <a href="<%= admirers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Admirers
  </a>
</div>
</center>

projects/scottiess/app/views/shared/_statsBIG.html.erb
<% @user ||= current_user %>
<div class="stats span7 hiv">
  <div class="stats">
  <a href="<%=user_path(@user)%>">
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
    </strong>
    Posts
  </a>
  <a href="<%= admirers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Admirers
  </a>
</div>

projects/scottiess/app/views/shared/_stats_profile.html.erb
<% @user ||= current_user %>
<div class="statss">
  <a href="<%=user_path(@user)%>">
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
    </strong>
    Posts
  </a> 
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Admiring
  </a>
  <a href="<%= admirers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Admirers
  </a>
</div>

projects/scottiess/app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
<center>  <%=image_tag current_user.image, :size => "250x250", :id=>"profilepicture", :title=> "You look amazing!" %> </center>
<h1><center>@<%= current_user.username %></center></h1>
</a>

projects/scottiess/app/views/shared/_user_navb.html.erb
<a href="<%= user_path(current_user) %>">
	<div class="row" id="aup">
	 <g><%= image_tag current_user.image, :size => "20x20", :id=>"usernavb"%> <%=current_user.username%></g>
	</div>
	</a>