projects/scottiess/config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from
    end
  end

  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'

   match '/course',  :to=> 'static_pages#courses'
    match '/bugs',  :to=> 'static_pages#bug'
    match '/teach',  :to=> 'static_pages#teach'
    match '/html5',  :to=> 'static_pages#les1'
     match '/android',  :to=> 'static_pages#les2'
 match '/home',  :to=> 'static_pages#home'
  root      :to=> 'users#index'

end

projects/scottiess/app/views/layouts/_footer.html.erb
<% if signed_in? %>
<% else %>
<footer class="footer">
  <small>
    Copyright
    <x>2013</x> <a href="http://orangeapps.weebly.com/" target="_blank"> OrangeApps</a><x>, All rights reserved.</x>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <!--li><%= link_to "Contact", contact_path %></li-->
      <li><a href="http://orangeapps.weebly.com/news" target="_blank">News</a></li>
    </ul>
  </nav>
</footer>
<% end %>

projects/scottiess/app/views/layouts/_header.html.erb
<% if signed_in? %>
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navigatebar-inner">
  <div class="container">
    <nav>
      <%= link_to image_tag("icon.png", :id=> "logo"), root_path  %>
    <ul class="nav pull-right menu">
      
      <li><%= render 'shared/user_navb'%></li>
      <li><%= link_to image_tag("2.png", :size => "20x20", :id=>"usernavb" ), root_path, :id=> "text" %></li>
        <li><%= link_to image_tag("1.png", :size => "20x20", :id=>"usernavb")  , users_path, :id=> "text" %></li>
        <li id="msg-menu" class="dropdown">
          <a href="#" class = "dropdown-toggle" data-toggle="dropdown" style="color: #ffffff;background-color: #212121">
            <%= image_tag("5.png", :size => "20x20", :id=>"usernavb") %>
          </a>
          <ul class="dropdown-menu menu">
            <li><%= link_to "Inbox", messages_to_user_path(current_user) %></li>
            <li><%= link_to "Outbox", messages_from_user_path(current_user) %></li>
          </ul>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff;background-color: #212121">
             <%= image_tag("3.png", :size => "20x20", :id=>"usernavb") %>
          </a>
          <ul class="dropdown-menu menu">
           
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>            <li class="divider"> </li>
            <li>
            <%= link_to "Sign out", signout_path, :method=> :delete %>
            </li>
          </ul>
        </li>
    </ul>
    </nav>
  </div>
</div>
</header>
<% end %>

projects/scottiess/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/stylesheets/bootstrap-responsive.css" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", :media=> "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shim/googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39121685-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
  <body>
    
    <div class="container">
      <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>